# Generated by Django 5.2.3 on 2025-06-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omar', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
