# Generated by Django 5.2.3 on 2025-06-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omar', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omar.project'),
        ),
    ]
