# Generated by Django 5.2.3 on 2025-06-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omar', '0004_profile_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='profile_img',
            new_name='profile_img2',
        ),
    ]
